spring:
  datasource:
    url: jdbc:postgresql://${PG_HOST:172.17.0.1}:${PG_PORT:5431}/managementDB
    username: ${PG_USER:postgres}
    password: ${PG_PASS:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
  docker:
    compose:
      enabled: false