spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/managementDB
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
#    database: postgresql
  #    database-platform: org.hibernate.dialect.PostgreSQLDialect
  docker:
    compose:
      enabled: false

logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm.jdbc.bind: trace
      springframework:
        cache: trace
        orm.jpa.JpaTransactionManager: debug
        security: trace